# config file version
apiVersion: 2

datasources:
{% for name, datasource in salt['pillar.get']('grafana:datasources:prometheus').items() %}
- name: {{ name }}
  type: prometheus
  access: proxy
  url: {{ datasource.url }}
  basicAuth: False
  isDefault: {{ loop.first }}
  editable: true
  jsonData:
    timeInterval: 5s
{% endfor %}
